baseurl = "https://guilhermealbm.com"
title = "Guilherme Miranda"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "guilhermealbm"

[markup.highlight]
style = "github-dark"

[params]
  author = "Guilherme Miranda"
  info = "Android Software Engineer"
  description = "Guilherme's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "https://avatars.githubusercontent.com/u/42358828"
  #gravatar = "contact@guilhermealbm.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2025

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Linkedin"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 1
  url = "https://linkedin.com/in/guilhermealbm"
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/guilhermealbm/"
[[params.social]]
  name = "Bluesky"
  icon = "fa-brands fa-bluesky fa-2x"
  weight = 3
  url = "https://bsky.app/profile/guilhermealbm.bsky.social"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"

[[menu.main]]
  name = "CV"
  weight = 2
  url = "https://guilhermealbm.com/guilherme_miranda_cv.pdf"

[caches]
  [caches.images]
    dir = ':cacheDir/images'